lib/school_web/router.ex
defmodule SchoolWeb.Router do
  use SchoolWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SchoolWeb do
    pipe_through :browser

    get "/", PageController, :index
  resources "/course", CourseController
  get "/view/:id", CourseController, :view
  resources "/student", StudentController
  post "/lecturer", LecturerController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", SchoolWeb do
  #   pipe_through :api
  # end
end

lib/school/management/course.ex
defmodule School.Management.Course do
  use Ecto.Schema
  import Ecto.Changeset
  alias School.Management.Student

  schema "courses" do
    field :code, :integer
    field :credits, :integer
    field :department, :string
    field :title, :string
    has_many :lecturers, School.Lecture.Lecturer
    many_to_many(
      :students,
     Student,
      join_through: "requests",
      on_replace: :delete
)


    timestamps()
  end

  @doc false
  def changeset(course, attrs) do
    course
    |> cast(attrs, [:title, :code, :credits, :department])
    |> validate_required([:title, :code, :credits, :department])
  end
end

lib/school_web/controllers/course_controller.ex
defmodule SchoolWeb.CourseController do
  use SchoolWeb, :controller
alias  School.Management.Student
alias School.Management.Course
alias School.Management
alias School.Lecture
alias School.Lecture.Lecturer

  def index(conn, _params) do
    course = Management.list_courses

   # course2 =  Management.list_physics_courses
    render(conn, "index.html",  course: course  )
  end

  def show(conn, %{"id" => id}) do
   course = Management.get_course!(id)
    lecturer_changeset = Lecture.change_lecturer(%Lecturer{})
    render(conn, "show.html", course: course, lecturer_changeset: lecturer_changeset)
  end

end

lib/school_web/views/course_view.ex
defmodule SchoolWeb.CourseView do
  use SchoolWeb, :view
end

lib/school_web/templates/course/index.html.eex
<div class="column main-pane">


  <div class= "content-pane">
<div class="title-text">Courses</div>

 <table class="table table-striped table-hover trans-table column col-11 col-mx-auto">
      <thead>
        <tr>
          <th class="code">Code</th>
          <th class="title">Title</th>
          <th class="credits">Credits</th>
           <th>Action</th>
        </tr>
      </thead>
      <tbody>
      <%= for course <- @course do %>
         <tr>
    
<td class="id"><%= course.code %></td>
<td class="id"><%= course.title %></td>
<td class="id"><%= course.credits %></td>
<td class="id"> <%= link "Show", to: Routes.course_path(@conn, :show, course) %> </td>


         </tr>
         
         <% end %>
       </tbody>
    </table>

<div class="course-count"></div>






</div>
</div></div>

lib/school_web/templates/course/show.html.eex
<div class="column main-pane">


  <div class= "content-pane">
<div class="title-text">Course Details</div>
<p><span class="title"><b>Title: </b></span><%=  @course.title %></p>
<p><span class="code"><b>Code: </b></span><%=  @course.code  %></p>

<p><span class="department"><b>Department: </b></span><%=  @course.department  %></p>

<div class ="ac">
<button class="accordion1 t1">Students Registered </button>
<div class="panel">
  <p><%=  @course.students|>Enum.map(&(&1.name)) |> Enum.join(", ")  %></p>
</div>

<button class="accordion1 t2">Lecturers Registered</button>
<div class="panel">
  <p><%=  @course.lecturers|>Enum.map(&(&1.name)) |> Enum.join(", ")  %></p>

<div class="addon">
  <p><b>Add Lecturer</b><p>
  <div class ="columns">
   <div class ="column col-4">
<%= form_for @lecturer_changeset, Routes.lecturer_path(@conn, :create), fn f -> %>
  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>
  </div>
   <div class ="column col-8">
  <div>
  <button type="submit" class= "btn btn-dim ">Add</button>
  </div>
  <%= hidden_input f, :course_id, value: @course.id %>
<% end %>
</div> </div>
</div>
</div>





  </div>
    </div>

lib/school_web/templates/course/view.html.eex
<div class="column main-pane">


  <div class= "content-pane">
<div class="title-text"> Selected Courses </div>
<table class="table table-striped table-hover trans-table column col-11 col-mx-auto">
      <thead>
        <tr>
          <th>Code</th>
          <th>Title</th>
          <th>Credits</th>
           <th>Action</th>
        </tr>
      </thead>
      <tbody>
<%= for course <- @student.courses do %>
         <tr>

<td class="id"><%= course.code %></td>
<td class="id"><%= course.title %></td>
<td class="id"><%= course.credits %></td>
<td class="id"> <%= link "Delete", to: Routes.course_path(@conn, :delete, course), class: "btn btn-primary", method: :delete, data: [confirm: "Are you sure?"] %></td>


         </tr>
           
         <% end %>
       </tbody>
    </table>

<div class="course-count"></div>
 
<span class="btn btn-primary" style="margin-top:20px"><a style="color:white" href="/courses"> Add More Courses</a></span>
</div>
</div>